# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Southern Gothic Codex
tagline:          'An Investigation of the past'
description:      'We found something that we want to share with you'
url:              http://thesoutherngothiccodex.com
baseurl:          /

author:
  name:           'Patrick & Ryan'
  url:            https://twitter.com/thesnarkyone

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
